# =============================================================================
#  Auto-generated by Sync Tool - builds a synced timeline in DaVinci Resolve.
#  Run in Resolve:  Workspace > Console > Py3, or Workspace > Scripts.
#  Non-destructive: no media file is modified. Delete the timeline to revert.
# =============================================================================
import csv, os, time

CSV_PATH      = r"__CSV_PATH__"
TIMELINE_NAME = "Synced Timeline"
FPS           = 25
LEAD_SECONDS  = 3          # blank handle before the first clip

def frames_to_tc(fr, fps):
    s = int(fr / fps); f = int(fr - s * fps)
    return f"{s//3600:02d}:{s%3600//60:02d}:{s%60:02d}:{f:02d}"

try:
    resolve
except NameError:
    import DaVinciResolveScript as dvr
    resolve = dvr.scriptapp("Resolve")

proj = resolve.GetProjectManager().GetCurrentProject()
if not proj:
    raise SystemExit("Open a project in Resolve first.")
mp = proj.GetMediaPool(); rootf = mp.GetRootFolder()

rows = [r for r in csv.DictReader(open(CSV_PATH, newline="", encoding="utf-8"))
        if os.path.isfile(r["path"])]
if not rows:
    raise SystemExit("No usable rows in " + CSV_PATH)
print("rows:", len(rows))

positions = [float(r["position_s"]) for r in rows]
start_f   = int(round((min(positions) - LEAD_SECONDS) * FPS))
START_TC  = frames_to_tc(start_f, FPS)

proj.SetSetting("timelineFrameRate", str(FPS))

# --- import media into bins by group -----------------------------------------
def get_bin(name):
    for sub in rootf.GetSubFolderList():
        if sub.GetName() == name:
            return sub
    return mp.AddSubFolder(rootf, name)

bins = {}
for r in rows:
    bins.setdefault(r["group"] or "media", []).append(r["path"])

item_by_path = {}
for name, paths in bins.items():
    mp.SetCurrentFolder(get_bin(name.replace("/", "_").replace("\\", "_") or "media"))
    for it in (mp.ImportMedia(paths) or []):
        item_by_path[it.GetClipProperty("File Path")] = it
        item_by_path[it.GetClipProperty("File Name")] = it
print("imported:", len(bins), "bins")

# --- wait for Resolve to read clip lengths (else clips land zero-length) -----
def frames_of(it):
    try: return int(it.GetClipProperty("Frames"))
    except Exception: return 0
items = list({id(v): v for v in item_by_path.values()}.values())
for _ in range(40):
    if all(frames_of(i) > 1 for i in items): break
    time.sleep(0.5)

# --- timeline ----------------------------------------------------------------
tl = mp.CreateEmptyTimeline(TIMELINE_NAME)
if not tl:
    raise SystemExit("Timeline '%s' already exists - delete or rename it." % TIMELINE_NAME)
proj.SetCurrentTimeline(tl)
tl.SetStartTimecode("00:00:00:00")        # zero base: recordFrame is unambiguous
nv = max([int(r["track"]) for r in rows if r["kind"] == "video"] or [1])
na = max([int(r["track"]) for r in rows if r["kind"] == "audio"] or [1])
while tl.GetTrackCount("video") < nv: tl.AddTrack("video")
while tl.GetTrackCount("audio") < na: tl.AddTrack("audio")
for r in rows:                              # user-defined track names
    try: tl.SetTrackName(r["kind"], int(r["track"]),
                         r.get("track_name") or r["group"] or r["kind"])
    except Exception: pass

# --- apply clip metadata so it is searchable/visible inside Resolve ----------
META_MAP = {"scene": "Scene", "shot": "Shot", "angle": "Angle",
            "reel": "Reel Name", "comments": "Comments", "keywords": "Keywords"}
meta_n, color_n = 0, 0
for r in rows:
    it = item_by_path.get(r["path"]) or item_by_path.get(os.path.basename(r["path"]))
    if not it:
        continue
    for key, field in META_MAP.items():
        val = (r.get(key) or "").strip()
        if val:
            try:
                if it.SetMetadata(field, val):
                    meta_n += 1
            except Exception:
                pass
    col = (r.get("color") or "").strip()
    if col:
        try:
            if it.SetClipColor(col):
                color_n += 1
        except Exception:
            pass
if meta_n or color_n:
    print(f"metadata applied: {meta_n} fields, {color_n} clip colours")

vclips, aclips, missing = [], [], 0
for r in rows:
    it = item_by_path.get(r["path"]) or item_by_path.get(os.path.basename(r["path"]))
    if not it:
        missing += 1; continue
    rec = int(round(float(r["position_s"]) * FPS)) - start_f
    if rec < 0: continue
    nf = frames_of(it)
    if nf <= 1:
        fps_src = float(r["fps"]) if r.get("fps") else FPS
        nf = max(2, int(round(float(r["dur_s"]) * fps_src)))
    info = {"mediaPoolItem": it, "startFrame": 0, "endFrame": nf - 1,
            "recordFrame": rec, "trackIndex": int(r["track"]),
            "mediaType": 1 if r["kind"] == "video" else 2}
    (vclips if r["kind"] == "video" else aclips).append(info)

pv = mp.AppendToTimeline(vclips) if vclips else []
pa = mp.AppendToTimeline(aclips) if aclips else []

print("-" * 58)
print(f"video placed {len(pv)}/{len(vclips)} | audio placed {len(pa)}/{len(aclips)}")
if missing: print("missing items:", missing)
length = tl.GetEndFrame() - tl.GetStartFrame()
print("TIMELINE LENGTH:", length, "frames =", frames_to_tc(length, FPS))
print("  --> non-zero means the clips are really there. Press \\ to Zoom to Fit."
      if length > 1 else "  --> zero length: clips did not commit.")
try:
    tl.SetStartTimecode(START_TC)          # cosmetic: ruler reads time-of-day
    print("ruler start set to", START_TC)
except Exception:
    pass
